title: ITU Operational Bulletin
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com


ob_root: '_issues'

# TODO: Move to itu-ob-data
message_types:
  custom:
    contents: load_file

  amendment: {}

  running_annexes:
    title:
      en: Lists annexed to the ITU Operational Bulletin
      ru: Списки, прилагаемые к Оперативному бюллетеню МСЭ

  approved_recommendations:
    title:
      en: Approval of ITU-T Recommendations
      ru: Утверждение Рекомендаций МСЭ-T

  sanc:
    title:
      en: Assignment of Signalling Area/Network Codes (SANC)
      ru: (TBD sanc-ru)

  iptn:
    title:
      en: The International Public Telecommunication Numbering Plan
      ru: Международный план нумерации электросвязи общего пользования

  telephone_service:
    title:
      en: Telephone Service
      ru: Услуга телефонной связи

  service_restrictions:
    title:
      en: Service Restrictions
      ru: Ограничения обслуживания

  callback_procedures:
    title:
      en: "Call-back and alternative calling procedures (Res. 21 Rev. PP-2006)"
      ru: "Обратный вызов и альтернативные процедуры вызова (Рез. 21 (Пересм. ПК-06))"


languages:
  - id: en
    title: English
  - id: ru
    title: Russian

default_language: en

# Build settings
markdown: kramdown

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
exclude:
  - data
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
